<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="../TestProject.props" />
  <ItemGroup>
    <ProjectReference Include="../../RealJapanese/Repositories/Repositories.csproj" />
    <ProjectReference Include="../../RealJapanese/Genki.Generation/Genki.Generation.csproj" />
  </ItemGroup>
</Project>
