param([ValidateSet('core','dotnet','rider')][string[]]$Modules = @('core','dotnet'))
$ErrorActionPreference = 'Stop'
$root = Split-Path $PSScriptRoot -Parent
$config = Join-Path $root '.codex/config.toml'
$banner = '# Generated by tooling/configure.ps1. Edit tooling/modules/*.toml, then regenerate.'
if ((Test-Path $config) -and !(Get-Content $config -First 1).StartsWith($banner)) {
    throw 'Refusing to overwrite an unmanaged Codex configuration. Merge the module fragments manually.'
}
$parts = @($banner)
foreach ($module in ($Modules | Select-Object -Unique)) {
    $parts += Get-Content "$PSScriptRoot/modules/$module.toml" -Raw
}
New-Item -ItemType Directory -Force (Split-Path $config) | Out-Null
[IO.File]::WriteAllText($config, ($parts -join "`n`n") + "`n", [Text.UTF8Encoding]::new($false))
Write-Output "Configured modules: $($Modules -join ', ')"
